disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "msegoviadev"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"

[params.author]
  name = "msegoviadev"
  email = "hello@msegovia.dev"
  image = "img/msegoviadev_glitch.gif"
  headline = "Senior Software Engineer in ðŸ‡¨ðŸ‡­ aus ðŸ‡ªðŸ‡¸"
  bio = "Software enthusiast. Not replaced by AI (yet). Fueled by curiosity and good coffee."
  links = [
    { email = "mailto:hello@msegovia.dev" },
    { x-twitter = "https://x.com/msegoviadev" },
    { github = "https://github.com/msegoviadev" },
    { linkedin = "https://www.linkedin.com/in/msegoviadev" },
  ]
